# Generated by Django 2.0.2 on 2018-03-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.RunSQL(
        """
        drop table if exists exchange_user;
        drop table if exists exchange_orders;
        drop table if exists exchange_userorders;
        drop table if exists exchange_stocks;

        """
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=255)),
                ('stock_id', models.IntegerField()),
                ('limit_price', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('user_order_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.RunSQL(
        """
        INSERT INTO exchange_user (user_id, email, password) VALUES (1, 'test1@gmail.com', 'password');

        """),
         migrations.RunSQL(
        """
        INSERT INTO exchange_user (user_id, email, password) VALUES (2, 'test2@gmail.com', 'password');

        """),
        migrations.RunSQL(
        """
        INSERT INTO exchange_stocks (stock_id, stock_name, price) VALUES (1, 'GOOG', 256.99);

        """),
    ]
